// <auto-generated />
using System;
using MentalHealthApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentalHealthApp.Migrations
{
    [DbContext(typeof(MentalHealthContext))]
    [Migration("20251004123135_nullable")]
    partial class nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MentalHealthApp.Models.CustomUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastMoodCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PfpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Badge = "None",
                            ConcurrencyStamp = "ffe0e36f-8730-4c13-a116-93792ac922f8",
                            CurrentStreak = 0,
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            LongestStreak = 0,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECqGRk3WeqPIolPRchAsoVMXk37XQCCb3k7JfIh7vKCUXW3q04GsiImrVHzH7qiPDg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e80e84a3-54eb-4307-897d-16dcaa74ff5d",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Badge = "None",
                            ConcurrencyStamp = "a7874d0c-1b62-4ce2-be9d-750d5c07f06d",
                            CurrentStreak = 0,
                            Email = "admin2@example.com",
                            EmailConfirmed = true,
                            FirstName = "Second",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            LongestStreak = 0,
                            NormalizedEmail = "ADMIN2@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJPrFm20BboiTo2S60aJWSVE3egISXVFOrBuQ4SnoQV3ybH1GlcVMUEiEV8sSVG3sQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62f399bd-9dcc-40fb-9f92-c5031dea8921",
                            TwoFactorEnabled = false,
                            UserName = "admin2@example.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            Badge = "None",
                            ConcurrencyStamp = "511b045b-83c8-4ec4-9dc2-96f0a0e13809",
                            CurrentStreak = 0,
                            Email = "admin3@example.com",
                            EmailConfirmed = true,
                            FirstName = "Third",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            LongestStreak = 0,
                            NormalizedEmail = "ADMIN3@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN3@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIs7ux5Xipw/VrVp8cjUrUv5qw3xF77EolO5F9PjQGWZxjbnhqOFCSxLhzvfNOug4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45239553-c9af-483d-a59d-d73d0f45663e",
                            TwoFactorEnabled = false,
                            UserName = "admin3@example.com"
                        },
                        new
                        {
                            Id = "14",
                            AccessFailedCount = 0,
                            Badge = "Bronze",
                            ConcurrencyStamp = "0cfd2768-3297-48af-a4a3-a1d47578698d",
                            CurrentStreak = 1,
                            Email = "patient1@example.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            LastMoodCheckIn = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "Smith",
                            LockoutEnabled = false,
                            LongestStreak = 2,
                            NormalizedEmail = "PATIENT1@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK2dvVnFwY1c7XZgHG7g0oAppKnIRnn7z+qzmtGfM/ggxa0X+QcBjLgEmxxfjdJqiQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e6abc78d-8a45-4e72-a6a3-27c2506c9601",
                            TwoFactorEnabled = false,
                            UserName = "patient1@example.com"
                        },
                        new
                        {
                            Id = "15",
                            AccessFailedCount = 0,
                            Badge = "Bronze",
                            ConcurrencyStamp = "c16c07a0-fac8-4a80-b5db-f467b6829a1c",
                            CurrentStreak = 1,
                            Email = "patient2@example.com",
                            EmailConfirmed = true,
                            FirstName = "Mike",
                            LastMoodCheckIn = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            LongestStreak = 1,
                            NormalizedEmail = "PATIENT2@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFRrQd5Z+82GrvtNL2wdSDyY7e2KjfyCVqSK/gAd4oB1Xu3claZNmQfRuObFeZutJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "026d76ca-2ff8-40fb-8eb3-79b1bb588b80",
                            TwoFactorEnabled = false,
                            UserName = "patient2@example.com"
                        },
                        new
                        {
                            Id = "16",
                            AccessFailedCount = 0,
                            Badge = "Bronze",
                            ConcurrencyStamp = "88761cad-2c5a-43b4-a97a-9bf6793f8cd0",
                            CurrentStreak = 1,
                            Email = "patient3@example.com",
                            EmailConfirmed = true,
                            FirstName = "Emily",
                            LastMoodCheckIn = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "Williams",
                            LockoutEnabled = false,
                            LongestStreak = 1,
                            NormalizedEmail = "PATIENT3@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT3@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFWp6ljtAjc9hqocQm/KwmUOxnAtGcDZC8DlEe0Ly9VLRyeIREmfAcVSaHluwvhE5g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ad911836-b7cd-41c1-9e81-ac620aeb295b",
                            TwoFactorEnabled = false,
                            UserName = "patient3@example.com"
                        },
                        new
                        {
                            Id = "17",
                            AccessFailedCount = 0,
                            Badge = "Bronze",
                            ConcurrencyStamp = "c2eeb5b8-354b-452b-9c03-8389704c054a",
                            CurrentStreak = 1,
                            Email = "patient4@example.com",
                            EmailConfirmed = true,
                            FirstName = "David",
                            LastMoodCheckIn = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "Lee",
                            LockoutEnabled = false,
                            LongestStreak = 1,
                            NormalizedEmail = "PATIENT4@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT4@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELYCmGvpnhHxbCPPIQzkbCn9a0rMtIh7KBtk8R40ngY0jii03surq2OCZMlzMMyjag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e919aaef-a785-4a26-88c6-47f53285c28c",
                            TwoFactorEnabled = false,
                            UserName = "patient4@example.com"
                        },
                        new
                        {
                            Id = "18",
                            AccessFailedCount = 0,
                            Badge = "Bronze",
                            ConcurrencyStamp = "be84f680-6112-45c0-9d25-d2752ca28baf",
                            CurrentStreak = 1,
                            Email = "patient5@example.com",
                            EmailConfirmed = true,
                            FirstName = "Sophia",
                            LastMoodCheckIn = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "Garcia",
                            LockoutEnabled = false,
                            LongestStreak = 1,
                            NormalizedEmail = "PATIENT5@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT5@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGS6n65QGFUxDGxV90puihDxpm2pFnUdZdprqLaRojUrpbNhxV13EFL173agvf3vTQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "534659fd-40ef-4db3-b68f-0f1a2bcc98d0",
                            TwoFactorEnabled = false,
                            UserName = "patient5@example.com"
                        },
                        new
                        {
                            Id = "19",
                            AccessFailedCount = 0,
                            Badge = "Bronze",
                            ConcurrencyStamp = "f5802ec6-c06d-4c3a-8a12-3cb13805cffe",
                            CurrentStreak = 1,
                            Email = "patient6@example.com",
                            EmailConfirmed = true,
                            FirstName = "James",
                            LastMoodCheckIn = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "Wilson",
                            LockoutEnabled = false,
                            LongestStreak = 1,
                            NormalizedEmail = "PATIENT6@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT6@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM1OnM2r6WpHwo7ExpTCaKZVwORCtfzfpcBxvhnZ4Qwnm8nVMH+SVS7bgqAUSVq46A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "666c8248-13ba-4e2a-b8aa-14b713be92f0",
                            TwoFactorEnabled = false,
                            UserName = "patient6@example.com"
                        },
                        new
                        {
                            Id = "20",
                            AccessFailedCount = 0,
                            Badge = "Bronze",
                            ConcurrencyStamp = "b32fbd09-bb2c-4b90-8b4c-8ce0b06f3cd2",
                            CurrentStreak = 1,
                            Email = "patient7@example.com",
                            EmailConfirmed = true,
                            FirstName = "Olivia",
                            LastMoodCheckIn = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            LastName = "Martinez",
                            LockoutEnabled = false,
                            LongestStreak = 1,
                            NormalizedEmail = "PATIENT7@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT7@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGdth/TjeOW8bfC02Mg63QAssQoSR8hGawR7GT+I6wGJkOy5Tn5xn7HGieOcVOOeJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "301b9383-3e13-4327-975b-87f84cb97426",
                            TwoFactorEnabled = false,
                            UserName = "patient7@example.com"
                        });
                });

            modelBuilder.Entity("MentalHealthApp.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddresseeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddresseeId = "15",
                            CreatedAt = new DateTime(2025, 9, 25, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6659),
                            RequesterId = "14",
                            RespondedAt = new DateTime(2025, 9, 26, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6686),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AddresseeId = "16",
                            CreatedAt = new DateTime(2025, 9, 27, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6692),
                            RequesterId = "14",
                            RespondedAt = new DateTime(2025, 9, 28, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6694),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AddresseeId = "14",
                            CreatedAt = new DateTime(2025, 9, 30, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6698),
                            RequesterId = "17",
                            RespondedAt = new DateTime(2025, 10, 1, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6701),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AddresseeId = "17",
                            CreatedAt = new DateTime(2025, 9, 23, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6705),
                            RequesterId = "15",
                            RespondedAt = new DateTime(2025, 9, 24, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6707),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AddresseeId = "15",
                            CreatedAt = new DateTime(2025, 10, 3, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6711),
                            RequesterId = "18",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AddresseeId = "19",
                            CreatedAt = new DateTime(2025, 9, 20, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6716),
                            RequesterId = "16",
                            RespondedAt = new DateTime(2025, 9, 21, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6718),
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            AddresseeId = "16",
                            CreatedAt = new DateTime(2025, 9, 28, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6723),
                            RequesterId = "20",
                            RespondedAt = new DateTime(2025, 9, 29, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6725),
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            AddresseeId = "19",
                            CreatedAt = new DateTime(2025, 9, 26, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6729),
                            RequesterId = "17",
                            RespondedAt = new DateTime(2025, 9, 27, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6732),
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            AddresseeId = "20",
                            CreatedAt = new DateTime(2025, 9, 24, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6736),
                            RequesterId = "18",
                            RespondedAt = new DateTime(2025, 9, 25, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6738),
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            AddresseeId = "20",
                            CreatedAt = new DateTime(2025, 9, 29, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6743),
                            RequesterId = "19",
                            RespondedAt = new DateTime(2025, 9, 30, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6745),
                            Status = 1
                        });
                });

            modelBuilder.Entity("MentalHealthApp.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hey Mike! How are you feeling today?",
                            IsRead = true,
                            ReceiverId = "15",
                            SenderId = "14",
                            SentAt = new DateTime(2025, 10, 3, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6802)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Hi Alice! I'm doing okay, just a bit stressed about work. How about you?",
                            IsRead = true,
                            ReceiverId = "14",
                            SenderId = "15",
                            SentAt = new DateTime(2025, 10, 3, 3, 31, 34, 146, DateTimeKind.Local).AddTicks(6811)
                        },
                        new
                        {
                            Id = 3,
                            Content = "I understand. Work has been tough for me too. Want to chat about it?",
                            IsRead = true,
                            ReceiverId = "15",
                            SenderId = "14",
                            SentAt = new DateTime(2025, 10, 3, 5, 31, 34, 146, DateTimeKind.Local).AddTicks(6816)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Emily! I saw your mood entry from yesterday. Are you doing better today?",
                            IsRead = true,
                            ReceiverId = "16",
                            SenderId = "14",
                            SentAt = new DateTime(2025, 10, 3, 13, 31, 34, 146, DateTimeKind.Local).AddTicks(6823)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Thanks for checking in, Alice. I'm feeling much better today! 😊",
                            IsRead = true,
                            ReceiverId = "14",
                            SenderId = "16",
                            SentAt = new DateTime(2025, 10, 3, 15, 31, 34, 146, DateTimeKind.Local).AddTicks(6828)
                        },
                        new
                        {
                            Id = 6,
                            Content = "David, how do you handle stress? I'm really struggling this week.",
                            IsRead = true,
                            ReceiverId = "17",
                            SenderId = "15",
                            SentAt = new DateTime(2025, 10, 2, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6832)
                        },
                        new
                        {
                            Id = 7,
                            Content = "I've been using the breathing exercises on the app. They really help! Want to try them together?",
                            IsRead = true,
                            ReceiverId = "15",
                            SenderId = "17",
                            SentAt = new DateTime(2025, 10, 2, 3, 31, 34, 146, DateTimeKind.Local).AddTicks(6836)
                        },
                        new
                        {
                            Id = 8,
                            Content = "James, I noticed we both had rough days yesterday. Want to support each other today?",
                            IsRead = true,
                            ReceiverId = "19",
                            SenderId = "16",
                            SentAt = new DateTime(2025, 10, 4, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6840)
                        },
                        new
                        {
                            Id = 9,
                            Content = "That would be great, Emily. It helps to know we're not alone in this.",
                            IsRead = true,
                            ReceiverId = "16",
                            SenderId = "19",
                            SentAt = new DateTime(2025, 10, 4, 3, 31, 34, 146, DateTimeKind.Local).AddTicks(6845)
                        },
                        new
                        {
                            Id = 10,
                            Content = "Olivia! I'm so proud of your mood streak! 🎉",
                            IsRead = false,
                            ReceiverId = "20",
                            SenderId = "18",
                            SentAt = new DateTime(2025, 10, 4, 13, 31, 34, 146, DateTimeKind.Local).AddTicks(6849)
                        },
                        new
                        {
                            Id = 11,
                            Content = "How's your pet doing, James? I've been thinking about you both.",
                            IsRead = false,
                            ReceiverId = "19",
                            SenderId = "17",
                            SentAt = new DateTime(2025, 10, 4, 19, 31, 34, 146, DateTimeKind.Local).AddTicks(6853)
                        },
                        new
                        {
                            Id = 12,
                            Content = "Remember to use the breathing exercise if you feel overwhelmed!",
                            IsRead = true,
                            ReceiverId = "15",
                            SenderId = "14",
                            SentAt = new DateTime(2025, 10, 4, 22, 31, 34, 146, DateTimeKind.Local).AddTicks(6857)
                        },
                        new
                        {
                            Id = 13,
                            Content = "Thanks for being such a good friend, Alice. It means a lot.",
                            IsRead = false,
                            ReceiverId = "14",
                            SenderId = "16",
                            SentAt = new DateTime(2025, 10, 5, 0, 31, 34, 146, DateTimeKind.Local).AddTicks(6862)
                        });
                });

            modelBuilder.Entity("MentalHealthApp.Models.MoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mood")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MoodEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 1,
                            Notes = "Had a great day with friends",
                            UserId = "14"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 4,
                            Notes = "Work stress is getting to me",
                            UserId = "14"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 6,
                            Notes = "Feeling calm after meditation",
                            UserId = "14"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 2,
                            Notes = "Feeling down today",
                            UserId = "15"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 5,
                            Notes = "Excited for upcoming trip",
                            UserId = "15"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 4,
                            Notes = "Stressed about work deadline",
                            UserId = "15"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 3,
                            Notes = "Angry about argument with friend",
                            UserId = "16"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 4,
                            Notes = "Exhausted from lack of sleep",
                            UserId = "16"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 6,
                            Notes = "Content with how things are going",
                            UserId = "16"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 2,
                            Notes = "Feeling lonely this weekend",
                            UserId = "17"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 1,
                            Notes = "Hopeful about therapy progress",
                            UserId = "17"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 6,
                            Notes = "Confused about my feelings",
                            UserId = "17"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 1,
                            Notes = "Happy about good news",
                            UserId = "18"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 4,
                            Notes = "Anxious about upcoming test",
                            UserId = "18"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 5,
                            Notes = "Excited to see family",
                            UserId = "19"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 6,
                            Notes = "Calm after yoga session",
                            UserId = "19"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 2,
                            Notes = "Sad about pet being sick",
                            UserId = "19"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 4,
                            Notes = "Tired from work week",
                            UserId = "20"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 6,
                            Notes = "Content with life right now",
                            UserId = "20"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Mood = 1,
                            Notes = "Hopeful about new treatment",
                            UserId = "20"
                        });
                });

            modelBuilder.Entity("MentalHealthApp.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("ConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationId");

                    b.HasIndex("SenderId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            CreatedAt = new DateTime(2025, 10, 3, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6924),
                            IsRead = false,
                            Message = "Sophia sent you a friend request",
                            SenderId = "18",
                            UserId = "15"
                        },
                        new
                        {
                            NotificationId = 2,
                            CreatedAt = new DateTime(2025, 10, 4, 13, 31, 34, 146, DateTimeKind.Local).AddTicks(6928),
                            IsRead = false,
                            Message = "New message from Sophia",
                            SenderId = "18",
                            UserId = "20"
                        },
                        new
                        {
                            NotificationId = 3,
                            CreatedAt = new DateTime(2025, 10, 4, 19, 31, 34, 146, DateTimeKind.Local).AddTicks(6931),
                            IsRead = false,
                            Message = "New message from David",
                            SenderId = "17",
                            UserId = "19"
                        },
                        new
                        {
                            NotificationId = 4,
                            CreatedAt = new DateTime(2025, 10, 5, 0, 31, 34, 146, DateTimeKind.Local).AddTicks(6934),
                            IsRead = false,
                            Message = "New message from Emily",
                            SenderId = "16",
                            UserId = "14"
                        });
                });

            modelBuilder.Entity("MentalHealthApp.Models.PlannerEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlannerEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 5, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(7039),
                            Description = "Jog in the park for 30 minutes",
                            EndTime = new DateTime(2025, 10, 5, 6, 30, 0, 0, DateTimeKind.Local),
                            EventType = 4,
                            IsCompleted = false,
                            Priority = 1,
                            StartTime = new DateTime(2025, 10, 5, 6, 0, 0, 0, DateTimeKind.Local),
                            Title = "Morning Jog",
                            UserId = "14"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 5, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(7048),
                            Description = "Weekly online therapy",
                            EndTime = new DateTime(2025, 10, 6, 15, 0, 0, 0, DateTimeKind.Local),
                            EventType = 5,
                            IsCompleted = false,
                            Priority = 2,
                            StartTime = new DateTime(2025, 10, 6, 14, 0, 0, 0, DateTimeKind.Local),
                            Title = "Therapy Session",
                            UserId = "14"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 5, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(7057),
                            Description = "Project planning meeting",
                            EndTime = new DateTime(2025, 10, 5, 11, 0, 0, 0, DateTimeKind.Local),
                            EventType = 3,
                            IsCompleted = false,
                            Priority = 2,
                            StartTime = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Local),
                            Title = "Work Meeting",
                            UserId = "15"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 5, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(7066),
                            Description = "Walk around neighborhood",
                            EndTime = new DateTime(2025, 10, 5, 18, 45, 0, 0, DateTimeKind.Local),
                            EventType = 5,
                            IsCompleted = false,
                            Priority = 0,
                            StartTime = new DateTime(2025, 10, 5, 18, 0, 0, 0, DateTimeKind.Local),
                            Title = "Evening Walk",
                            UserId = "15"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 5, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(7075),
                            Description = "Read for 1 hour before bed",
                            EndTime = new DateTime(2025, 10, 6, 21, 0, 0, 0, DateTimeKind.Local),
                            EventType = 7,
                            IsCompleted = false,
                            Priority = 0,
                            StartTime = new DateTime(2025, 10, 6, 20, 0, 0, 0, DateTimeKind.Local),
                            Title = "Read a Book",
                            UserId = "16"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 5, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(7090),
                            Description = "Strength training",
                            EndTime = new DateTime(2025, 10, 5, 8, 0, 0, 0, DateTimeKind.Local),
                            EventType = 5,
                            IsCompleted = false,
                            Priority = 1,
                            StartTime = new DateTime(2025, 10, 5, 7, 0, 0, 0, DateTimeKind.Local),
                            Title = "Gym Session",
                            UserId = "17"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 5, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(7100),
                            Description = "Morning meditation",
                            EndTime = new DateTime(2025, 10, 5, 7, 0, 0, 0, DateTimeKind.Local),
                            EventType = 4,
                            IsCompleted = false,
                            Priority = 1,
                            StartTime = new DateTime(2025, 10, 5, 6, 30, 0, 0, DateTimeKind.Local),
                            Title = "Meditation",
                            UserId = "18"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 5, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(7109),
                            Description = "Routine check-up",
                            EndTime = new DateTime(2025, 10, 7, 10, 0, 0, 0, DateTimeKind.Local),
                            EventType = 5,
                            IsCompleted = false,
                            Priority = 2,
                            StartTime = new DateTime(2025, 10, 7, 9, 0, 0, 0, DateTimeKind.Local),
                            Title = "Doctor Appointment",
                            UserId = "19"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 5, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(7117),
                            Description = "Work on homework",
                            EndTime = new DateTime(2025, 10, 5, 18, 0, 0, 0, DateTimeKind.Local),
                            EventType = 0,
                            IsCompleted = false,
                            Priority = 1,
                            StartTime = new DateTime(2025, 10, 5, 16, 0, 0, 0, DateTimeKind.Local),
                            Title = "Study Session",
                            UserId = "20"
                        });
                });

            modelBuilder.Entity("MentalHealthApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 6,
                            CreatedAt = new DateTime(2025, 10, 3, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6602),
                            Description = "Want to support our cause but rock some swag? This is the perfect choice for you!",
                            ImageUrl = "ShantiShirtMerch.png",
                            IsPrivate = false,
                            Name = "Shanti Black Tee",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2,
                            Category = 6,
                            CreatedAt = new DateTime(2025, 9, 29, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6607),
                            Description = "Get a fun plushy to be your companion!",
                            ImageUrl = "ShantiPlushy.jpg",
                            IsPrivate = false,
                            Name = "Shanti Plushy",
                            Price = 25m
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 7, 30, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6613),
                            Description = "A bestselling book with practical tips for mental wellness.",
                            ImageUrl = "Wellbook.jpg",
                            IsPrivate = false,
                            Name = "Wellness Book - 'Calm Your Mind'",
                            Price = 15.49m
                        },
                        new
                        {
                            Id = 4,
                            Category = 5,
                            CreatedAt = new DateTime(2025, 9, 21, 1, 31, 34, 146, DateTimeKind.Local).AddTicks(6622),
                            Description = "Includes stress balls, aroma oils, and calming teas.",
                            ImageUrl = "default-product.png",
                            IsPrivate = false,
                            Name = "Stress Relief Kit",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "14",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "15",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "16",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "17",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "18",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "19",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "20",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MentalHealthApp.Models.Friendship", b =>
                {
                    b.HasOne("MentalHealthApp.Models.CustomUser", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalHealthApp.Models.CustomUser", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("MentalHealthApp.Models.Message", b =>
                {
                    b.HasOne("MentalHealthApp.Models.CustomUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalHealthApp.Models.CustomUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MentalHealthApp.Models.Notification", b =>
                {
                    b.HasOne("MentalHealthApp.Models.CustomUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MentalHealthApp.Models.CustomUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalHealthApp.Models.PlannerEvent", b =>
                {
                    b.HasOne("MentalHealthApp.Models.CustomUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MentalHealthApp.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MentalHealthApp.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthApp.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MentalHealthApp.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
